//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ASTI_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/ASTI_DTO")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((this.CityIDField.Equals(value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASTI_Service.IASTI_Services")]
    public interface IASTI_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASTI_Services/SendMessage", ReplyAction="http://tempuri.org/IASTI_Services/SendMessageResponse")]
        void SendMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASTI_Services/SendMessage", ReplyAction="http://tempuri.org/IASTI_Services/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASTI_Services/GetCityes", ReplyAction="http://tempuri.org/IASTI_Services/GetCityesResponse")]
        ConsoleClient.ASTI_Service.City[] GetCityes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASTI_Services/GetCityes", ReplyAction="http://tempuri.org/IASTI_Services/GetCityesResponse")]
        System.Threading.Tasks.Task<ConsoleClient.ASTI_Service.City[]> GetCityesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IASTI_ServicesChannel : ConsoleClient.ASTI_Service.IASTI_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASTI_ServicesClient : System.ServiceModel.ClientBase<ConsoleClient.ASTI_Service.IASTI_Services>, ConsoleClient.ASTI_Service.IASTI_Services {
        
        public ASTI_ServicesClient() {
        }
        
        public ASTI_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASTI_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASTI_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASTI_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage() {
            base.Channel.SendMessage();
        }
        
        public System.Threading.Tasks.Task SendMessageAsync() {
            return base.Channel.SendMessageAsync();
        }
        
        public ConsoleClient.ASTI_Service.City[] GetCityes() {
            return base.Channel.GetCityes();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.ASTI_Service.City[]> GetCityesAsync() {
            return base.Channel.GetCityesAsync();
        }
    }
}
