//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService_A100")]
    public interface IService_A100 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/SendMessage", ReplyAction="http://tempuri.org/IService_A100/SendMessageResponse")]
        void SendMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/SendMessage", ReplyAction="http://tempuri.org/IService_A100/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/GetCityes", ReplyAction="http://tempuri.org/IService_A100/GetCityesResponse")]
        System.Collections.Generic.List<ASTI_DTO.City> GetCityes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/GetCityes", ReplyAction="http://tempuri.org/IService_A100/GetCityesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ASTI_DTO.City>> GetCityesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/GetString", ReplyAction="http://tempuri.org/IService_A100/GetStringResponse")]
        string GetString(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_A100/GetString", ReplyAction="http://tempuri.org/IService_A100/GetStringResponse")]
        System.Threading.Tasks.Task<string> GetStringAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_A100Channel : ConsoleClient.Service.IService_A100, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_A100Client : System.ServiceModel.ClientBase<ConsoleClient.Service.IService_A100>, ConsoleClient.Service.IService_A100 {
        
        public Service_A100Client() {
        }
        
        public Service_A100Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_A100Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_A100Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_A100Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage() {
            base.Channel.SendMessage();
        }
        
        public System.Threading.Tasks.Task SendMessageAsync() {
            return base.Channel.SendMessageAsync();
        }
        
        public System.Collections.Generic.List<ASTI_DTO.City> GetCityes() {
            return base.Channel.GetCityes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ASTI_DTO.City>> GetCityesAsync() {
            return base.Channel.GetCityesAsync();
        }
        
        public string GetString(string name) {
            return base.Channel.GetString(name);
        }
        
        public System.Threading.Tasks.Task<string> GetStringAsync(string name) {
            return base.Channel.GetStringAsync(name);
        }
    }
}
